[features]
seeds = false
skip-lint = false

[toolchain]
anchor_version = "0.31.1"

[programs.localnet]
wellswap_insurance = "27btQLJWLR8qNF28Lbp9QHD6bfGZwFMt4L2Rkn7STnXf"

[programs.devnet]
wellswap_insurance = "27btQLJWLR8qNF28Lbp9QHD6bfGZwFMt4L2Rkn7STnXf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/taewoongan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = ["programs/*"]

[build]
sbf = false
